import {Operatore} from "./Operatore";

export interface Ticket {
    id: string;
    stato_id: string;
    oggetto: string;
    corpo: string;
    charset_text: string;
    corpo_html: string;
    charset_html: string;
    path_allegati: string;
    anagrafica_id: string;
    anagrafica_rivenditore_id: string;
    produttore_id: string | null;
    reparto_id: string;
    priorita_id: string;
    tn: string;
    title: string | null;
    coda_id: string | null;
    registrazione: string | null;
    bloccato: string;
    email_destinatario: string;
    nome_destinatario: string;
    email_mittente: string;
    nome_mittente: string;
    richiesta_telefonica: string;
    raw: string | null;
    a: string;
    cc: string | null;
    bcc: string | null;
    corpo_text_blob: string | null;
    corpo_blob: string | null;
    data: string;
    data_abilitazione: string;
    data_disabilitazione: string | null;
    data_creazione: string;
    data_ultima_modifica: string;
    oggetto_iniziale: string;
    nticket: string;
    ragionesocialerichiedente: string;
    path_allegati_inline: string;
    risolto: string;
    datachiusura: string;
    utentegis: string | null;
    corpo_pulito: string | null;
    iuid: string;
    messageid: string;
    old_ticket_id: string | null;
    old_nticket: string | null;
    old_anagrafica_rivenditore_id: string | null;
    nome_stato: string;
    anagrafica_id_appartenenza: string;
    operatore: Operatore;
}